/*
 * Treezor API
 * Official endpoint documentation for Treezor.
 *
 * The version of the OpenAPI document: 24.11.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeleteWallet200ResponseWalletsInner
 */
public class DeleteWallet200ResponseWalletsInnerTest {
    private final DeleteWallet200ResponseWalletsInner model = new DeleteWallet200ResponseWalletsInner();

    /**
     * Model tests for DeleteWallet200ResponseWalletsInner
     */
    @Test
    public void testDeleteWallet200ResponseWalletsInner() {
        // TODO: test DeleteWallet200ResponseWalletsInner
    }

    /**
     * Test the property 'walletId'
     */
    @Test
    public void walletIdTest() {
        // TODO: test walletId
    }

    /**
     * Test the property 'walletTypeId'
     */
    @Test
    public void walletTypeIdTest() {
        // TODO: test walletTypeId
    }

    /**
     * Test the property 'walletStatus'
     */
    @Test
    public void walletStatusTest() {
        // TODO: test walletStatus
    }

    /**
     * Test the property 'codeStatus'
     */
    @Test
    public void codeStatusTest() {
        // TODO: test codeStatus
    }

    /**
     * Test the property 'informationStatus'
     */
    @Test
    public void informationStatusTest() {
        // TODO: test informationStatus
    }

    /**
     * Test the property 'walletTag'
     */
    @Test
    public void walletTagTest() {
        // TODO: test walletTag
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'userLastname'
     */
    @Test
    public void userLastnameTest() {
        // TODO: test userLastname
    }

    /**
     * Test the property 'userFirstname'
     */
    @Test
    public void userFirstnameTest() {
        // TODO: test userFirstname
    }

    /**
     * Test the property 'jointUserId'
     */
    @Test
    public void jointUserIdTest() {
        // TODO: test jointUserId
    }

    /**
     * Test the property 'tariffId'
     */
    @Test
    public void tariffIdTest() {
        // TODO: test tariffId
    }

    /**
     * Test the property 'eventName'
     */
    @Test
    public void eventNameTest() {
        // TODO: test eventName
    }

    /**
     * Test the property 'eventAlias'
     */
    @Test
    public void eventAliasTest() {
        // TODO: test eventAlias
    }

    /**
     * Test the property 'eventDate'
     */
    @Test
    public void eventDateTest() {
        // TODO: test eventDate
    }

    /**
     * Test the property 'eventMessage'
     */
    @Test
    public void eventMessageTest() {
        // TODO: test eventMessage
    }

    /**
     * Test the property 'eventPayinStartDate'
     */
    @Test
    public void eventPayinStartDateTest() {
        // TODO: test eventPayinStartDate
    }

    /**
     * Test the property 'eventPayinEndDate'
     */
    @Test
    public void eventPayinEndDateTest() {
        // TODO: test eventPayinEndDate
    }

    /**
     * Test the property 'contractSigned'
     */
    @Test
    public void contractSignedTest() {
        // TODO: test contractSigned
    }

    /**
     * Test the property 'bic'
     */
    @Test
    public void bicTest() {
        // TODO: test bic
    }

    /**
     * Test the property 'iban'
     */
    @Test
    public void ibanTest() {
        // TODO: test iban
    }

    /**
     * Test the property 'urlImage'
     */
    @Test
    public void urlImageTest() {
        // TODO: test urlImage
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'payinCount'
     */
    @Test
    public void payinCountTest() {
        // TODO: test payinCount
    }

    /**
     * Test the property 'payoutCount'
     */
    @Test
    public void payoutCountTest() {
        // TODO: test payoutCount
    }

    /**
     * Test the property 'transferCount'
     */
    @Test
    public void transferCountTest() {
        // TODO: test transferCount
    }

    /**
     * Test the property 'solde'
     */
    @Test
    public void soldeTest() {
        // TODO: test solde
    }

    /**
     * Test the property 'authorizedBalance'
     */
    @Test
    public void authorizedBalanceTest() {
        // TODO: test authorizedBalance
    }

    /**
     * Test the property 'totalRows'
     */
    @Test
    public void totalRowsTest() {
        // TODO: test totalRows
    }

}
