/*
 * Treezor API
 * Official endpoint documentation for Treezor.
 *
 * The version of the OpenAPI document: 24.11.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetCoCardTransactions200ResponseCardTransactionsInner
 */
public class GetCoCardTransactions200ResponseCardTransactionsInnerTest {
    private final GetCoCardTransactions200ResponseCardTransactionsInner model = new GetCoCardTransactions200ResponseCardTransactionsInner();

    /**
     * Model tests for GetCoCardTransactions200ResponseCardTransactionsInner
     */
    @Test
    public void testGetCoCardTransactions200ResponseCardTransactionsInner() {
        // TODO: test GetCoCardTransactions200ResponseCardTransactionsInner
    }

    /**
     * Test the property 'cardtransactionId'
     */
    @Test
    public void cardtransactionIdTest() {
        // TODO: test cardtransactionId
    }

    /**
     * Test the property 'cardId'
     */
    @Test
    public void cardIdTest() {
        // TODO: test cardId
    }

    /**
     * Test the property 'walletId'
     */
    @Test
    public void walletIdTest() {
        // TODO: test walletId
    }

    /**
     * Test the property 'acquirerId'
     */
    @Test
    public void acquirerIdTest() {
        // TODO: test acquirerId
    }

    /**
     * Test the property 'walletCurrency'
     */
    @Test
    public void walletCurrencyTest() {
        // TODO: test walletCurrency
    }

    /**
     * Test the property 'merchantId'
     */
    @Test
    public void merchantIdTest() {
        // TODO: test merchantId
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    public void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'merchantCity'
     */
    @Test
    public void merchantCityTest() {
        // TODO: test merchantCity
    }

    /**
     * Test the property 'merchantCountry'
     */
    @Test
    public void merchantCountryTest() {
        // TODO: test merchantCountry
    }

    /**
     * Test the property 'mccCode'
     */
    @Test
    public void mccCodeTest() {
        // TODO: test mccCode
    }

    /**
     * Test the property 'paymentLocalTime'
     */
    @Test
    public void paymentLocalTimeTest() {
        // TODO: test paymentLocalTime
    }

    /**
     * Test the property 'publicToken'
     */
    @Test
    public void publicTokenTest() {
        // TODO: test publicToken
    }

    /**
     * Test the property 'paymentAmount'
     */
    @Test
    public void paymentAmountTest() {
        // TODO: test paymentAmount
    }

    /**
     * Test the property 'paymentCurrency'
     */
    @Test
    public void paymentCurrencyTest() {
        // TODO: test paymentCurrency
    }

    /**
     * Test the property 'fees'
     */
    @Test
    public void feesTest() {
        // TODO: test fees
    }

    /**
     * Test the property 'paymentCountry'
     */
    @Test
    public void paymentCountryTest() {
        // TODO: test paymentCountry
    }

    /**
     * Test the property 'paymentId'
     */
    @Test
    public void paymentIdTest() {
        // TODO: test paymentId
    }

    /**
     * Test the property 'paymentStatus'
     */
    @Test
    public void paymentStatusTest() {
        // TODO: test paymentStatus
    }

    /**
     * Test the property 'paymentLocalAmount'
     */
    @Test
    public void paymentLocalAmountTest() {
        // TODO: test paymentLocalAmount
    }

    /**
     * Test the property 'posCardholderPresence'
     */
    @Test
    public void posCardholderPresenceTest() {
        // TODO: test posCardholderPresence
    }

    /**
     * Test the property 'posPostcode'
     */
    @Test
    public void posPostcodeTest() {
        // TODO: test posPostcode
    }

    /**
     * Test the property 'posCountry'
     */
    @Test
    public void posCountryTest() {
        // TODO: test posCountry
    }

    /**
     * Test the property 'posTerminalId'
     */
    @Test
    public void posTerminalIdTest() {
        // TODO: test posTerminalId
    }

    /**
     * Test the property 'posCardPresence'
     */
    @Test
    public void posCardPresenceTest() {
        // TODO: test posCardPresence
    }

    /**
     * Test the property 'panEntryMethod'
     */
    @Test
    public void panEntryMethodTest() {
        // TODO: test panEntryMethod
    }

    /**
     * Test the property 'authorizationNote'
     */
    @Test
    public void authorizationNoteTest() {
        // TODO: test authorizationNote
    }

    /**
     * Test the property 'authorizationResponseCode'
     */
    @Test
    public void authorizationResponseCodeTest() {
        // TODO: test authorizationResponseCode
    }

    /**
     * Test the property 'authorizationIssuerId'
     */
    @Test
    public void authorizationIssuerIdTest() {
        // TODO: test authorizationIssuerId
    }

    /**
     * Test the property 'authorizationIssuerTime'
     */
    @Test
    public void authorizationIssuerTimeTest() {
        // TODO: test authorizationIssuerTime
    }

    /**
     * Test the property 'authorizationMti'
     */
    @Test
    public void authorizationMtiTest() {
        // TODO: test authorizationMti
    }

    /**
     * Test the property 'authorizedBalance'
     */
    @Test
    public void authorizedBalanceTest() {
        // TODO: test authorizedBalance
    }

    /**
     * Test the property 'limitAtmYear'
     */
    @Test
    public void limitAtmYearTest() {
        // TODO: test limitAtmYear
    }

    /**
     * Test the property 'limitAtmMonth'
     */
    @Test
    public void limitAtmMonthTest() {
        // TODO: test limitAtmMonth
    }

    /**
     * Test the property 'limitAtmWeek'
     */
    @Test
    public void limitAtmWeekTest() {
        // TODO: test limitAtmWeek
    }

    /**
     * Test the property 'limitAtmDay'
     */
    @Test
    public void limitAtmDayTest() {
        // TODO: test limitAtmDay
    }

    /**
     * Test the property 'limitAtmAll'
     */
    @Test
    public void limitAtmAllTest() {
        // TODO: test limitAtmAll
    }

    /**
     * Test the property 'limitPaymentYear'
     */
    @Test
    public void limitPaymentYearTest() {
        // TODO: test limitPaymentYear
    }

    /**
     * Test the property 'limitPaymentMonth'
     */
    @Test
    public void limitPaymentMonthTest() {
        // TODO: test limitPaymentMonth
    }

    /**
     * Test the property 'limitPaymentWeek'
     */
    @Test
    public void limitPaymentWeekTest() {
        // TODO: test limitPaymentWeek
    }

    /**
     * Test the property 'limitPaymentDay'
     */
    @Test
    public void limitPaymentDayTest() {
        // TODO: test limitPaymentDay
    }

    /**
     * Test the property 'limitPaymentAll'
     */
    @Test
    public void limitPaymentAllTest() {
        // TODO: test limitPaymentAll
    }

    /**
     * Test the property 'totalLimitAtmYear'
     */
    @Test
    public void totalLimitAtmYearTest() {
        // TODO: test totalLimitAtmYear
    }

    /**
     * Test the property 'totalLimitAtmMonth'
     */
    @Test
    public void totalLimitAtmMonthTest() {
        // TODO: test totalLimitAtmMonth
    }

    /**
     * Test the property 'totalLimitAtmWeek'
     */
    @Test
    public void totalLimitAtmWeekTest() {
        // TODO: test totalLimitAtmWeek
    }

    /**
     * Test the property 'totalLimitAtmDay'
     */
    @Test
    public void totalLimitAtmDayTest() {
        // TODO: test totalLimitAtmDay
    }

    /**
     * Test the property 'totalLimitAtmAll'
     */
    @Test
    public void totalLimitAtmAllTest() {
        // TODO: test totalLimitAtmAll
    }

    /**
     * Test the property 'totalLimitPaymentYear'
     */
    @Test
    public void totalLimitPaymentYearTest() {
        // TODO: test totalLimitPaymentYear
    }

    /**
     * Test the property 'totalLimitPaymentMonth'
     */
    @Test
    public void totalLimitPaymentMonthTest() {
        // TODO: test totalLimitPaymentMonth
    }

    /**
     * Test the property 'totalLimitPaymentWeek'
     */
    @Test
    public void totalLimitPaymentWeekTest() {
        // TODO: test totalLimitPaymentWeek
    }

    /**
     * Test the property 'totalLimitPaymentDay'
     */
    @Test
    public void totalLimitPaymentDayTest() {
        // TODO: test totalLimitPaymentDay
    }

    /**
     * Test the property 'totalLimitPaymentAll'
     */
    @Test
    public void totalLimitPaymentAllTest() {
        // TODO: test totalLimitPaymentAll
    }

    /**
     * Test the property 'cardDigitalizationExternalId'
     */
    @Test
    public void cardDigitalizationExternalIdTest() {
        // TODO: test cardDigitalizationExternalId
    }

    /**
     * Test the property 'is3DS'
     */
    @Test
    public void is3DSTest() {
        // TODO: test is3DS
    }

    /**
     * Test the property 'merchantAddress'
     */
    @Test
    public void merchantAddressTest() {
        // TODO: test merchantAddress
    }

    /**
     * Test the property 'paymentLocalDate'
     */
    @Test
    public void paymentLocalDateTest() {
        // TODO: test paymentLocalDate
    }

    /**
     * Test the property 'optimizedMerchantName'
     */
    @Test
    public void optimizedMerchantNameTest() {
        // TODO: test optimizedMerchantName
    }

    /**
     * Test the property 'merchantLogo'
     */
    @Test
    public void merchantLogoTest() {
        // TODO: test merchantLogo
    }

    /**
     * Test the property 'merchantCategory'
     */
    @Test
    public void merchantCategoryTest() {
        // TODO: test merchantCategory
    }

    /**
     * Test the property 'transactionSubtype'
     */
    @Test
    public void transactionSubtypeTest() {
        // TODO: test transactionSubtype
    }

    /**
     * Test the property '_3dsExemptionType'
     */
    @Test
    public void _3dsExemptionTypeTest() {
        // TODO: test _3dsExemptionType
    }

    /**
     * Test the property 'receiverData'
     */
    @Test
    public void receiverDataTest() {
        // TODO: test receiverData
    }

    /**
     * Test the property 'senderData'
     */
    @Test
    public void senderDataTest() {
        // TODO: test senderData
    }

    /**
     * Test the property 'transactionTypeIdentifier'
     */
    @Test
    public void transactionTypeIdentifierTest() {
        // TODO: test transactionTypeIdentifier
    }

    /**
     * Test the property 'localMerchantId'
     */
    @Test
    public void localMerchantIdTest() {
        // TODO: test localMerchantId
    }

}
