/*
 * Treezor API
 * Official endpoint documentation for Treezor.
 *
 * The version of the OpenAPI document: 24.11.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetMassPayoutReportRef200Response
 */
public class GetMassPayoutReportRef200ResponseTest {
    private final GetMassPayoutReportRef200Response model = new GetMassPayoutReportRef200Response();

    /**
     * Model tests for GetMassPayoutReportRef200Response
     */
    @Test
    public void testGetMassPayoutReportRef200Response() {
        // TODO: test GetMassPayoutReportRef200Response
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'processedCreditors'
     */
    @Test
    public void processedCreditorsTest() {
        // TODO: test processedCreditors
    }

    /**
     * Test the property 'totalCreditors'
     */
    @Test
    public void totalCreditorsTest() {
        // TODO: test totalCreditors
    }

}
