/*
 * Treezor API
 * Official endpoint documentation for Treezor.
 *
 * The version of the OpenAPI document: 24.11.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostUsersRequest
 */
public class PostUsersRequestTest {
    private final PostUsersRequest model = new PostUsersRequest();

    /**
     * Model tests for PostUsersRequest
     */
    @Test
    public void testPostUsersRequest() {
        // TODO: test PostUsersRequest
    }

    /**
     * Test the property 'userTypeId'
     */
    @Test
    public void userTypeIdTest() {
        // TODO: test userTypeId
    }

    /**
     * Test the property 'userTag'
     */
    @Test
    public void userTagTest() {
        // TODO: test userTag
    }

    /**
     * Test the property 'parentUserId'
     */
    @Test
    public void parentUserIdTest() {
        // TODO: test parentUserId
    }

    /**
     * Test the property 'parentType'
     */
    @Test
    public void parentTypeTest() {
        // TODO: test parentType
    }

    /**
     * Test the property 'specifiedUSPerson'
     */
    @Test
    public void specifiedUSPersonTest() {
        // TODO: test specifiedUSPerson
    }

    /**
     * Test the property 'controllingPersonType'
     */
    @Test
    public void controllingPersonTypeTest() {
        // TODO: test controllingPersonType
    }

    /**
     * Test the property 'employeeType'
     */
    @Test
    public void employeeTypeTest() {
        // TODO: test employeeType
    }

    /**
     * Test the property 'entityType'
     */
    @Test
    public void entityTypeTest() {
        // TODO: test entityType
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'firstname'
     */
    @Test
    public void firstnameTest() {
        // TODO: test firstname
    }

    /**
     * Test the property 'lastname'
     */
    @Test
    public void lastnameTest() {
        // TODO: test lastname
    }

    /**
     * Test the property 'middleNames'
     */
    @Test
    public void middleNamesTest() {
        // TODO: test middleNames
    }

    /**
     * Test the property 'birthday'
     */
    @Test
    public void birthdayTest() {
        // TODO: test birthday
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'address1'
     */
    @Test
    public void address1Test() {
        // TODO: test address1
    }

    /**
     * Test the property 'address2'
     */
    @Test
    public void address2Test() {
        // TODO: test address2
    }

    /**
     * Test the property 'address3'
     */
    @Test
    public void address3Test() {
        // TODO: test address3
    }

    /**
     * Test the property 'postcode'
     */
    @Test
    public void postcodeTest() {
        // TODO: test postcode
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'distributionCountry'
     */
    @Test
    public void distributionCountryTest() {
        // TODO: test distributionCountry
    }

    /**
     * Test the property 'secondaryAddress1'
     */
    @Test
    public void secondaryAddress1Test() {
        // TODO: test secondaryAddress1
    }

    /**
     * Test the property 'secondaryAddress2'
     */
    @Test
    public void secondaryAddress2Test() {
        // TODO: test secondaryAddress2
    }

    /**
     * Test the property 'secondaryAddress3'
     */
    @Test
    public void secondaryAddress3Test() {
        // TODO: test secondaryAddress3
    }

    /**
     * Test the property 'secondaryPostcode'
     */
    @Test
    public void secondaryPostcodeTest() {
        // TODO: test secondaryPostcode
    }

    /**
     * Test the property 'secondaryCity'
     */
    @Test
    public void secondaryCityTest() {
        // TODO: test secondaryCity
    }

    /**
     * Test the property 'secondaryState'
     */
    @Test
    public void secondaryStateTest() {
        // TODO: test secondaryState
    }

    /**
     * Test the property 'secondaryCountry'
     */
    @Test
    public void secondaryCountryTest() {
        // TODO: test secondaryCountry
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'mobile'
     */
    @Test
    public void mobileTest() {
        // TODO: test mobile
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    public void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'nationalityOther'
     */
    @Test
    public void nationalityOtherTest() {
        // TODO: test nationalityOther
    }

    /**
     * Test the property 'placeOfBirth'
     */
    @Test
    public void placeOfBirthTest() {
        // TODO: test placeOfBirth
    }

    /**
     * Test the property 'birthCountry'
     */
    @Test
    public void birthCountryTest() {
        // TODO: test birthCountry
    }

    /**
     * Test the property 'occupation'
     */
    @Test
    public void occupationTest() {
        // TODO: test occupation
    }

    /**
     * Test the property 'incomeRange'
     */
    @Test
    public void incomeRangeTest() {
        // TODO: test incomeRange
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    public void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'legalRegistrationNumber'
     */
    @Test
    public void legalRegistrationNumberTest() {
        // TODO: test legalRegistrationNumber
    }

    /**
     * Test the property 'legalTvaNumber'
     */
    @Test
    public void legalTvaNumberTest() {
        // TODO: test legalTvaNumber
    }

    /**
     * Test the property 'legalRegistrationDate'
     */
    @Test
    public void legalRegistrationDateTest() {
        // TODO: test legalRegistrationDate
    }

    /**
     * Test the property 'legalForm'
     */
    @Test
    public void legalFormTest() {
        // TODO: test legalForm
    }

    /**
     * Test the property 'legalShareCapital'
     */
    @Test
    public void legalShareCapitalTest() {
        // TODO: test legalShareCapital
    }

    /**
     * Test the property 'legalSector'
     */
    @Test
    public void legalSectorTest() {
        // TODO: test legalSector
    }

    /**
     * Test the property 'legalAnnualTurnOver'
     */
    @Test
    public void legalAnnualTurnOverTest() {
        // TODO: test legalAnnualTurnOver
    }

    /**
     * Test the property 'legalNetIncomeRange'
     */
    @Test
    public void legalNetIncomeRangeTest() {
        // TODO: test legalNetIncomeRange
    }

    /**
     * Test the property 'legalNumberOfEmployeeRange'
     */
    @Test
    public void legalNumberOfEmployeeRangeTest() {
        // TODO: test legalNumberOfEmployeeRange
    }

    /**
     * Test the property 'effectiveBeneficiary'
     */
    @Test
    public void effectiveBeneficiaryTest() {
        // TODO: test effectiveBeneficiary
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'taxNumber'
     */
    @Test
    public void taxNumberTest() {
        // TODO: test taxNumber
    }

    /**
     * Test the property 'taxResidence'
     */
    @Test
    public void taxResidenceTest() {
        // TODO: test taxResidence
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'personalAssets'
     */
    @Test
    public void personalAssetsTest() {
        // TODO: test personalAssets
    }

    /**
     * Test the property 'activityOutsideEu'
     */
    @Test
    public void activityOutsideEuTest() {
        // TODO: test activityOutsideEu
    }

    /**
     * Test the property 'economicSanctions'
     */
    @Test
    public void economicSanctionsTest() {
        // TODO: test economicSanctions
    }

    /**
     * Test the property 'residentCountriesSanctions'
     */
    @Test
    public void residentCountriesSanctionsTest() {
        // TODO: test residentCountriesSanctions
    }

    /**
     * Test the property 'involvedSanctions'
     */
    @Test
    public void involvedSanctionsTest() {
        // TODO: test involvedSanctions
    }

    /**
     * Test the property 'entitySanctionsQuestionnaire'
     */
    @Test
    public void entitySanctionsQuestionnaireTest() {
        // TODO: test entitySanctionsQuestionnaire
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'occupationType'
     */
    @Test
    public void occupationTypeTest() {
        // TODO: test occupationType
    }

    /**
     * Test the property 'sourceOfFunds'
     */
    @Test
    public void sourceOfFundsTest() {
        // TODO: test sourceOfFunds
    }

    /**
     * Test the property 'legalSectorType'
     */
    @Test
    public void legalSectorTypeTest() {
        // TODO: test legalSectorType
    }

    /**
     * Test the property 'isOnStockExchange'
     */
    @Test
    public void isOnStockExchangeTest() {
        // TODO: test isOnStockExchange
    }

    /**
     * Test the property 'webauthn'
     */
    @Test
    public void webauthnTest() {
        // TODO: test webauthn
    }

    /**
     * Test the property 'passcode'
     */
    @Test
    public void passcodeTest() {
        // TODO: test passcode
    }

    /**
     * Test the property 'occupationCategory'
     */
    @Test
    public void occupationCategoryTest() {
        // TODO: test occupationCategory
    }

    /**
     * Test the property 'personalAssetsRange'
     */
    @Test
    public void personalAssetsRangeTest() {
        // TODO: test personalAssetsRange
    }

    /**
     * Test the property 'monthlyIncomeRange'
     */
    @Test
    public void monthlyIncomeRangeTest() {
        // TODO: test monthlyIncomeRange
    }

}
