/*
 * Treezor API
 * Official endpoint documentation for Treezor.
 *
 * The version of the OpenAPI document: 24.11.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PostPayout200ResponsePayoutsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostPayout200Response
 */
public class PostPayout200ResponseTest {
    private final PostPayout200Response model = new PostPayout200Response();

    /**
     * Model tests for PostPayout200Response
     */
    @Test
    public void testPostPayout200Response() {
        // TODO: test PostPayout200Response
    }

    /**
     * Test the property 'payouts'
     */
    @Test
    public void payoutsTest() {
        // TODO: test payouts
    }

}
