/*
 * Treezor API
 * Official endpoint documentation for Treezor.
 *
 * The version of the OpenAPI document: 24.11.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PutRecallRRequest
 */
public class PutRecallRRequestTest {
    private final PutRecallRRequest model = new PutRecallRRequest();

    /**
     * Model tests for PutRecallRRequest
     */
    @Test
    public void testPutRecallRRequest() {
        // TODO: test PutRecallRRequest
    }

    /**
     * Test the property 'accessSignature'
     */
    @Test
    public void accessSignatureTest() {
        // TODO: test accessSignature
    }

    /**
     * Test the property 'accessTag'
     */
    @Test
    public void accessTagTest() {
        // TODO: test accessTag
    }

    /**
     * Test the property 'accessUserId'
     */
    @Test
    public void accessUserIdTest() {
        // TODO: test accessUserId
    }

    /**
     * Test the property 'accessUserIp'
     */
    @Test
    public void accessUserIpTest() {
        // TODO: test accessUserIp
    }

    /**
     * Test the property 'responseType'
     */
    @Test
    public void responseTypeTest() {
        // TODO: test responseType
    }

    /**
     * Test the property 'negativeResponseReasonCode'
     */
    @Test
    public void negativeResponseReasonCodeTest() {
        // TODO: test negativeResponseReasonCode
    }

    /**
     * Test the property 'negativeResponseAdditionalInformation'
     */
    @Test
    public void negativeResponseAdditionalInformationTest() {
        // TODO: test negativeResponseAdditionalInformation
    }

    /**
     * Test the property 'responseComment'
     */
    @Test
    public void responseCommentTest() {
        // TODO: test responseComment
    }

}
