/*
 * Treezor API
 * Official endpoint documentation for Treezor.
 *
 * The version of the OpenAPI document: 24.11.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PostVirtualIbanRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T10:05:33.742486471+01:00[Europe/Paris]", comments = "Generator version: 7.10.0")
public class PostVirtualIbanRequest {
  public static final String SERIALIZED_NAME_WALLET_ID = "walletId";
  @SerializedName(SERIALIZED_NAME_WALLET_ID)
  @javax.annotation.Nonnull
  private Integer walletId;

  /**
   * The type of IBAN, allowing for a specific transfer direction.  Can be: &lt;ul&gt;&lt;li&gt;&#x60;1&#x60; for &#x60;SDDR&#x60; [SEPA Direct Debit](/guide/transfers/direct-debit.html)&lt;/li&gt;&lt;li&gt;&#x60;2&#x60; for &#x60;SCTR&#x60; [SEPA Credit Transfer](/guide/transfers/credit-transfer.html#received-credit-transfers-sctr)&lt;/li&gt;&lt;/ul&gt; 
   */
  @JsonAdapter(TypeIdEnum.Adapter.class)
  public enum TypeIdEnum {
    NUMBER_1(1),
    
    NUMBER_2(2);

    private Integer value;

    TypeIdEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeIdEnum fromValue(Integer value) {
      for (TypeIdEnum b : TypeIdEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeIdEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeIdEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeIdEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return TypeIdEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      Integer value = jsonElement.getAsInt();
      TypeIdEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE_ID = "typeId";
  @SerializedName(SERIALIZED_NAME_TYPE_ID)
  @javax.annotation.Nonnull
  private TypeIdEnum typeId;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  @javax.annotation.Nullable
  private String tag;

  public static final String SERIALIZED_NAME_VALID_FROM = "validFrom";
  @SerializedName(SERIALIZED_NAME_VALID_FROM)
  @javax.annotation.Nullable
  private String validFrom;

  public static final String SERIALIZED_NAME_VALID_TO = "validTo";
  @SerializedName(SERIALIZED_NAME_VALID_TO)
  @javax.annotation.Nullable
  private String validTo;

  public static final String SERIALIZED_NAME_MAX_USAGE = "maxUsage";
  @SerializedName(SERIALIZED_NAME_MAX_USAGE)
  @javax.annotation.Nullable
  private Integer maxUsage;

  public static final String SERIALIZED_NAME_MAX_AMOUNT = "maxAmount";
  @SerializedName(SERIALIZED_NAME_MAX_AMOUNT)
  @javax.annotation.Nullable
  private Float maxAmount;

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  @javax.annotation.Nullable
  private String reference;

  public PostVirtualIbanRequest() {
  }

  public PostVirtualIbanRequest walletId(@javax.annotation.Nonnull Integer walletId) {
    this.walletId = walletId;
    return this;
  }

  /**
   * The unique identifier of the Wallet to which the Virtual IBAN is associated. Must be a &#x60;walletType&#x60; of &#x60;9&#x60; or &#x60;10&#x60;. 
   * @return walletId
   */
  @javax.annotation.Nonnull
  public Integer getWalletId() {
    return walletId;
  }

  public void setWalletId(@javax.annotation.Nonnull Integer walletId) {
    this.walletId = walletId;
  }


  public PostVirtualIbanRequest typeId(@javax.annotation.Nonnull TypeIdEnum typeId) {
    this.typeId = typeId;
    return this;
  }

  /**
   * The type of IBAN, allowing for a specific transfer direction.  Can be: &lt;ul&gt;&lt;li&gt;&#x60;1&#x60; for &#x60;SDDR&#x60; [SEPA Direct Debit](/guide/transfers/direct-debit.html)&lt;/li&gt;&lt;li&gt;&#x60;2&#x60; for &#x60;SCTR&#x60; [SEPA Credit Transfer](/guide/transfers/credit-transfer.html#received-credit-transfers-sctr)&lt;/li&gt;&lt;/ul&gt; 
   * @return typeId
   */
  @javax.annotation.Nonnull
  public TypeIdEnum getTypeId() {
    return typeId;
  }

  public void setTypeId(@javax.annotation.Nonnull TypeIdEnum typeId) {
    this.typeId = typeId;
  }


  public PostVirtualIbanRequest tag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
    return this;
  }

  /**
   * Custom attribute that you can use as you see fit.  Learn more in the [Object tags](/guide/api-basics/objects-tags.html) article. 
   * @return tag
   */
  @javax.annotation.Nullable
  public String getTag() {
    return tag;
  }

  public void setTag(@javax.annotation.Nullable String tag) {
    this.tag = tag;
  }


  public PostVirtualIbanRequest validFrom(@javax.annotation.Nullable String validFrom) {
    this.validFrom = validFrom;
    return this;
  }

  /**
   * The date from which the Virtual IBAN validity starts. Defaults to today&#39;s date and must be set in the future.&lt;br&gt; Format: YYYY-MM-DD 
   * @return validFrom
   */
  @javax.annotation.Nullable
  public String getValidFrom() {
    return validFrom;
  }

  public void setValidFrom(@javax.annotation.Nullable String validFrom) {
    this.validFrom = validFrom;
  }


  public PostVirtualIbanRequest validTo(@javax.annotation.Nullable String validTo) {
    this.validTo = validTo;
    return this;
  }

  /**
   * The date from which the Virtual IBAN validity ends. Must be set after the &#x60;validFrom&#x60; date.&lt;br&gt; Format: YYYY-MM-DD 
   * @return validTo
   */
  @javax.annotation.Nullable
  public String getValidTo() {
    return validTo;
  }

  public void setValidTo(@javax.annotation.Nullable String validTo) {
    this.validTo = validTo;
  }


  public PostVirtualIbanRequest maxUsage(@javax.annotation.Nullable Integer maxUsage) {
    this.maxUsage = maxUsage;
    return this;
  }

  /**
   * The maximum number of transactions allowed (&#x60;0&#x60; &#x3D; unlimited).  
   * @return maxUsage
   */
  @javax.annotation.Nullable
  public Integer getMaxUsage() {
    return maxUsage;
  }

  public void setMaxUsage(@javax.annotation.Nullable Integer maxUsage) {
    this.maxUsage = maxUsage;
  }


  public PostVirtualIbanRequest maxAmount(@javax.annotation.Nullable Float maxAmount) {
    this.maxAmount = maxAmount;
    return this;
  }

  /**
   * The maximum cumulated amount of all transactions (&#x60;\&quot;0.00\&quot;&#x60; &#x3D; unlimited). 
   * @return maxAmount
   */
  @javax.annotation.Nullable
  public Float getMaxAmount() {
    return maxAmount;
  }

  public void setMaxAmount(@javax.annotation.Nullable Float maxAmount) {
    this.maxAmount = maxAmount;
  }


  public PostVirtualIbanRequest reference(@javax.annotation.Nullable String reference) {
    this.reference = reference;
    return this;
  }

  /**
   * Custom field for your internal reference of the Virtual IBAN.  Max. length: 255 characters. 
   * @return reference
   */
  @javax.annotation.Nullable
  public String getReference() {
    return reference;
  }

  public void setReference(@javax.annotation.Nullable String reference) {
    this.reference = reference;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostVirtualIbanRequest postVirtualIbanRequest = (PostVirtualIbanRequest) o;
    return Objects.equals(this.walletId, postVirtualIbanRequest.walletId) &&
        Objects.equals(this.typeId, postVirtualIbanRequest.typeId) &&
        Objects.equals(this.tag, postVirtualIbanRequest.tag) &&
        Objects.equals(this.validFrom, postVirtualIbanRequest.validFrom) &&
        Objects.equals(this.validTo, postVirtualIbanRequest.validTo) &&
        Objects.equals(this.maxUsage, postVirtualIbanRequest.maxUsage) &&
        Objects.equals(this.maxAmount, postVirtualIbanRequest.maxAmount) &&
        Objects.equals(this.reference, postVirtualIbanRequest.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(walletId, typeId, tag, validFrom, validTo, maxUsage, maxAmount, reference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostVirtualIbanRequest {\n");
    sb.append("    walletId: ").append(toIndentedString(walletId)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    maxUsage: ").append(toIndentedString(maxUsage)).append("\n");
    sb.append("    maxAmount: ").append(toIndentedString(maxAmount)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("walletId");
    openapiFields.add("typeId");
    openapiFields.add("tag");
    openapiFields.add("validFrom");
    openapiFields.add("validTo");
    openapiFields.add("maxUsage");
    openapiFields.add("maxAmount");
    openapiFields.add("reference");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("walletId");
    openapiRequiredFields.add("typeId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostVirtualIbanRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostVirtualIbanRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostVirtualIbanRequest is not found in the empty JSON string", PostVirtualIbanRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostVirtualIbanRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PostVirtualIbanRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostVirtualIbanRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `typeId`
      TypeIdEnum.validateJsonElement(jsonObj.get("typeId"));
      if ((jsonObj.get("tag") != null && !jsonObj.get("tag").isJsonNull()) && !jsonObj.get("tag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tag").toString()));
      }
      if ((jsonObj.get("validFrom") != null && !jsonObj.get("validFrom").isJsonNull()) && !jsonObj.get("validFrom").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `validFrom` to be a primitive type in the JSON string but got `%s`", jsonObj.get("validFrom").toString()));
      }
      if ((jsonObj.get("validTo") != null && !jsonObj.get("validTo").isJsonNull()) && !jsonObj.get("validTo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `validTo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("validTo").toString()));
      }
      if ((jsonObj.get("maxAmount") != null && !jsonObj.get("maxAmount").isJsonNull()) && !jsonObj.get("maxAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `maxAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maxAmount").toString()));
      }
      if ((jsonObj.get("reference") != null && !jsonObj.get("reference").isJsonNull()) && !jsonObj.get("reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reference").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostVirtualIbanRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostVirtualIbanRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostVirtualIbanRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostVirtualIbanRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PostVirtualIbanRequest>() {
           @Override
           public void write(JsonWriter out, PostVirtualIbanRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostVirtualIbanRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostVirtualIbanRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostVirtualIbanRequest
   * @throws IOException if the JSON string is invalid with respect to PostVirtualIbanRequest
   */
  public static PostVirtualIbanRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostVirtualIbanRequest.class);
  }

  /**
   * Convert an instance of PostVirtualIbanRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

