/*
 * Treezor API
 * Official endpoint documentation for Treezor.
 *
 * The version of the OpenAPI document: 24.11.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PutRecallSctInst201Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T10:05:33.742486471+01:00[Europe/Paris]", comments = "Generator version: 7.10.0")
public class PutRecallSctInst201Response {
  public static final String SERIALIZED_NAME_RECALL_I_D = "recallID";
  @SerializedName(SERIALIZED_NAME_RECALL_I_D)
  @javax.annotation.Nullable
  private String recallID;

  public PutRecallSctInst201Response() {
  }

  public PutRecallSctInst201Response recallID(@javax.annotation.Nullable String recallID) {
    this.recallID = recallID;
    return this;
  }

  /**
   * Get recallID
   * @return recallID
   */
  @javax.annotation.Nullable
  public String getRecallID() {
    return recallID;
  }

  public void setRecallID(@javax.annotation.Nullable String recallID) {
    this.recallID = recallID;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutRecallSctInst201Response putRecallSctInst201Response = (PutRecallSctInst201Response) o;
    return Objects.equals(this.recallID, putRecallSctInst201Response.recallID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recallID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutRecallSctInst201Response {\n");
    sb.append("    recallID: ").append(toIndentedString(recallID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("recallID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PutRecallSctInst201Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PutRecallSctInst201Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PutRecallSctInst201Response is not found in the empty JSON string", PutRecallSctInst201Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PutRecallSctInst201Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PutRecallSctInst201Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("recallID") != null && !jsonObj.get("recallID").isJsonNull()) && !jsonObj.get("recallID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `recallID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recallID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PutRecallSctInst201Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PutRecallSctInst201Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PutRecallSctInst201Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PutRecallSctInst201Response.class));

       return (TypeAdapter<T>) new TypeAdapter<PutRecallSctInst201Response>() {
           @Override
           public void write(JsonWriter out, PutRecallSctInst201Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PutRecallSctInst201Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PutRecallSctInst201Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PutRecallSctInst201Response
   * @throws IOException if the JSON string is invalid with respect to PutRecallSctInst201Response
   */
  public static PutRecallSctInst201Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PutRecallSctInst201Response.class);
  }

  /**
   * Convert an instance of PutRecallSctInst201Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

