/*
 * Treezor API
 * Official endpoint documentation for Treezor.
 *
 * The version of the OpenAPI document: 24.11.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ScaWalletObjectScaWalletsInnerMobileWallet
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-26T10:05:33.742486471+01:00[Europe/Paris]", comments = "Generator version: 7.10.0")
public class ScaWalletObjectScaWalletsInnerMobileWallet {
  public static final String SERIALIZED_NAME_APP_BUILD_NUMBER = "appBuildNumber";
  @SerializedName(SERIALIZED_NAME_APP_BUILD_NUMBER)
  @javax.annotation.Nullable
  private String appBuildNumber;

  public static final String SERIALIZED_NAME_SDK_VERSION = "sdkVersion";
  @SerializedName(SERIALIZED_NAME_SDK_VERSION)
  @javax.annotation.Nullable
  private String sdkVersion;

  public static final String SERIALIZED_NAME_OS = "os";
  @SerializedName(SERIALIZED_NAME_OS)
  @javax.annotation.Nullable
  private String os;

  public static final String SERIALIZED_NAME_OS_VERSION = "osVersion";
  @SerializedName(SERIALIZED_NAME_OS_VERSION)
  @javax.annotation.Nullable
  private String osVersion;

  public static final String SERIALIZED_NAME_BRAND = "brand";
  @SerializedName(SERIALIZED_NAME_BRAND)
  @javax.annotation.Nullable
  private String brand;

  public static final String SERIALIZED_NAME_PRODUCT_MODEL = "productModel";
  @SerializedName(SERIALIZED_NAME_PRODUCT_MODEL)
  @javax.annotation.Nullable
  private String productModel;

  public static final String SERIALIZED_NAME_DEVICE_ID = "deviceId";
  @SerializedName(SERIALIZED_NAME_DEVICE_ID)
  @javax.annotation.Nullable
  private String deviceId;

  public static final String SERIALIZED_NAME_DEVICE_ID_TYPE = "deviceIdType";
  @SerializedName(SERIALIZED_NAME_DEVICE_ID_TYPE)
  @javax.annotation.Nullable
  private String deviceIdType;

  public static final String SERIALIZED_NAME_PRODUCT_FINGERPRINT = "productFingerprint";
  @SerializedName(SERIALIZED_NAME_PRODUCT_FINGERPRINT)
  @javax.annotation.Nullable
  private String productFingerprint;

  public static final String SERIALIZED_NAME_SECRET_FINGERPRINT = "secretFingerprint";
  @SerializedName(SERIALIZED_NAME_SECRET_FINGERPRINT)
  @javax.annotation.Nullable
  private String secretFingerprint;

  public static final String SERIALIZED_NAME_ROOT = "root";
  @SerializedName(SERIALIZED_NAME_ROOT)
  @javax.annotation.Nullable
  private String root;

  public static final String SERIALIZED_NAME_PUSH_MESSAGING_ID = "pushMessagingId";
  @SerializedName(SERIALIZED_NAME_PUSH_MESSAGING_ID)
  @javax.annotation.Nullable
  private String pushMessagingId;

  public static final String SERIALIZED_NAME_PUSH_MESSAGING_PROVIDER = "pushMessagingProvider";
  @SerializedName(SERIALIZED_NAME_PUSH_MESSAGING_PROVIDER)
  @javax.annotation.Nullable
  private String pushMessagingProvider;

  public static final String SERIALIZED_NAME_MOBILE_UPDATE_DATE = "mobileUpdateDate";
  @SerializedName(SERIALIZED_NAME_MOBILE_UPDATE_DATE)
  @javax.annotation.Nullable
  private String mobileUpdateDate;

  public static final String SERIALIZED_NAME_LAST_ELIGIBILITY_CHECK = "lastEligibilityCheck";
  @SerializedName(SERIALIZED_NAME_LAST_ELIGIBILITY_CHECK)
  @javax.annotation.Nullable
  private OffsetDateTime lastEligibilityCheck;

  public static final String SERIALIZED_NAME_NFC = "nfc";
  @SerializedName(SERIALIZED_NAME_NFC)
  @javax.annotation.Nullable
  private Boolean nfc;

  public static final String SERIALIZED_NAME_EMULATOR = "emulator";
  @SerializedName(SERIALIZED_NAME_EMULATOR)
  @javax.annotation.Nullable
  private Boolean emulator;

  public static final String SERIALIZED_NAME_APPLE_TEAM_ID = "appleTeamId";
  @SerializedName(SERIALIZED_NAME_APPLE_TEAM_ID)
  @javax.annotation.Nullable
  private String appleTeamId;

  public ScaWalletObjectScaWalletsInnerMobileWallet() {
  }

  public ScaWalletObjectScaWalletsInnerMobileWallet appBuildNumber(@javax.annotation.Nullable String appBuildNumber) {
    this.appBuildNumber = appBuildNumber;
    return this;
  }

  /**
   * Get appBuildNumber
   * @return appBuildNumber
   */
  @javax.annotation.Nullable
  public String getAppBuildNumber() {
    return appBuildNumber;
  }

  public void setAppBuildNumber(@javax.annotation.Nullable String appBuildNumber) {
    this.appBuildNumber = appBuildNumber;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet sdkVersion(@javax.annotation.Nullable String sdkVersion) {
    this.sdkVersion = sdkVersion;
    return this;
  }

  /**
   * Get sdkVersion
   * @return sdkVersion
   */
  @javax.annotation.Nullable
  public String getSdkVersion() {
    return sdkVersion;
  }

  public void setSdkVersion(@javax.annotation.Nullable String sdkVersion) {
    this.sdkVersion = sdkVersion;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet os(@javax.annotation.Nullable String os) {
    this.os = os;
    return this;
  }

  /**
   * Get os
   * @return os
   */
  @javax.annotation.Nullable
  public String getOs() {
    return os;
  }

  public void setOs(@javax.annotation.Nullable String os) {
    this.os = os;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet osVersion(@javax.annotation.Nullable String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

  /**
   * Get osVersion
   * @return osVersion
   */
  @javax.annotation.Nullable
  public String getOsVersion() {
    return osVersion;
  }

  public void setOsVersion(@javax.annotation.Nullable String osVersion) {
    this.osVersion = osVersion;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet brand(@javax.annotation.Nullable String brand) {
    this.brand = brand;
    return this;
  }

  /**
   * Get brand
   * @return brand
   */
  @javax.annotation.Nullable
  public String getBrand() {
    return brand;
  }

  public void setBrand(@javax.annotation.Nullable String brand) {
    this.brand = brand;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet productModel(@javax.annotation.Nullable String productModel) {
    this.productModel = productModel;
    return this;
  }

  /**
   * Get productModel
   * @return productModel
   */
  @javax.annotation.Nullable
  public String getProductModel() {
    return productModel;
  }

  public void setProductModel(@javax.annotation.Nullable String productModel) {
    this.productModel = productModel;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet deviceId(@javax.annotation.Nullable String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * Get deviceId
   * @return deviceId
   */
  @javax.annotation.Nullable
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(@javax.annotation.Nullable String deviceId) {
    this.deviceId = deviceId;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet deviceIdType(@javax.annotation.Nullable String deviceIdType) {
    this.deviceIdType = deviceIdType;
    return this;
  }

  /**
   * Get deviceIdType
   * @return deviceIdType
   */
  @javax.annotation.Nullable
  public String getDeviceIdType() {
    return deviceIdType;
  }

  public void setDeviceIdType(@javax.annotation.Nullable String deviceIdType) {
    this.deviceIdType = deviceIdType;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet productFingerprint(@javax.annotation.Nullable String productFingerprint) {
    this.productFingerprint = productFingerprint;
    return this;
  }

  /**
   * Get productFingerprint
   * @return productFingerprint
   */
  @javax.annotation.Nullable
  public String getProductFingerprint() {
    return productFingerprint;
  }

  public void setProductFingerprint(@javax.annotation.Nullable String productFingerprint) {
    this.productFingerprint = productFingerprint;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet secretFingerprint(@javax.annotation.Nullable String secretFingerprint) {
    this.secretFingerprint = secretFingerprint;
    return this;
  }

  /**
   * Get secretFingerprint
   * @return secretFingerprint
   */
  @javax.annotation.Nullable
  public String getSecretFingerprint() {
    return secretFingerprint;
  }

  public void setSecretFingerprint(@javax.annotation.Nullable String secretFingerprint) {
    this.secretFingerprint = secretFingerprint;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet root(@javax.annotation.Nullable String root) {
    this.root = root;
    return this;
  }

  /**
   * Get root
   * @return root
   */
  @javax.annotation.Nullable
  public String getRoot() {
    return root;
  }

  public void setRoot(@javax.annotation.Nullable String root) {
    this.root = root;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet pushMessagingId(@javax.annotation.Nullable String pushMessagingId) {
    this.pushMessagingId = pushMessagingId;
    return this;
  }

  /**
   * Get pushMessagingId
   * @return pushMessagingId
   */
  @javax.annotation.Nullable
  public String getPushMessagingId() {
    return pushMessagingId;
  }

  public void setPushMessagingId(@javax.annotation.Nullable String pushMessagingId) {
    this.pushMessagingId = pushMessagingId;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet pushMessagingProvider(@javax.annotation.Nullable String pushMessagingProvider) {
    this.pushMessagingProvider = pushMessagingProvider;
    return this;
  }

  /**
   * Get pushMessagingProvider
   * @return pushMessagingProvider
   */
  @javax.annotation.Nullable
  public String getPushMessagingProvider() {
    return pushMessagingProvider;
  }

  public void setPushMessagingProvider(@javax.annotation.Nullable String pushMessagingProvider) {
    this.pushMessagingProvider = pushMessagingProvider;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet mobileUpdateDate(@javax.annotation.Nullable String mobileUpdateDate) {
    this.mobileUpdateDate = mobileUpdateDate;
    return this;
  }

  /**
   * Get mobileUpdateDate
   * @return mobileUpdateDate
   */
  @javax.annotation.Nullable
  public String getMobileUpdateDate() {
    return mobileUpdateDate;
  }

  public void setMobileUpdateDate(@javax.annotation.Nullable String mobileUpdateDate) {
    this.mobileUpdateDate = mobileUpdateDate;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet lastEligibilityCheck(@javax.annotation.Nullable OffsetDateTime lastEligibilityCheck) {
    this.lastEligibilityCheck = lastEligibilityCheck;
    return this;
  }

  /**
   * Get lastEligibilityCheck
   * @return lastEligibilityCheck
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastEligibilityCheck() {
    return lastEligibilityCheck;
  }

  public void setLastEligibilityCheck(@javax.annotation.Nullable OffsetDateTime lastEligibilityCheck) {
    this.lastEligibilityCheck = lastEligibilityCheck;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet nfc(@javax.annotation.Nullable Boolean nfc) {
    this.nfc = nfc;
    return this;
  }

  /**
   * Get nfc
   * @return nfc
   */
  @javax.annotation.Nullable
  public Boolean getNfc() {
    return nfc;
  }

  public void setNfc(@javax.annotation.Nullable Boolean nfc) {
    this.nfc = nfc;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet emulator(@javax.annotation.Nullable Boolean emulator) {
    this.emulator = emulator;
    return this;
  }

  /**
   * Get emulator
   * @return emulator
   */
  @javax.annotation.Nullable
  public Boolean getEmulator() {
    return emulator;
  }

  public void setEmulator(@javax.annotation.Nullable Boolean emulator) {
    this.emulator = emulator;
  }


  public ScaWalletObjectScaWalletsInnerMobileWallet appleTeamId(@javax.annotation.Nullable String appleTeamId) {
    this.appleTeamId = appleTeamId;
    return this;
  }

  /**
   * Get appleTeamId
   * @return appleTeamId
   */
  @javax.annotation.Nullable
  public String getAppleTeamId() {
    return appleTeamId;
  }

  public void setAppleTeamId(@javax.annotation.Nullable String appleTeamId) {
    this.appleTeamId = appleTeamId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScaWalletObjectScaWalletsInnerMobileWallet scaWalletObjectScaWalletsInnerMobileWallet = (ScaWalletObjectScaWalletsInnerMobileWallet) o;
    return Objects.equals(this.appBuildNumber, scaWalletObjectScaWalletsInnerMobileWallet.appBuildNumber) &&
        Objects.equals(this.sdkVersion, scaWalletObjectScaWalletsInnerMobileWallet.sdkVersion) &&
        Objects.equals(this.os, scaWalletObjectScaWalletsInnerMobileWallet.os) &&
        Objects.equals(this.osVersion, scaWalletObjectScaWalletsInnerMobileWallet.osVersion) &&
        Objects.equals(this.brand, scaWalletObjectScaWalletsInnerMobileWallet.brand) &&
        Objects.equals(this.productModel, scaWalletObjectScaWalletsInnerMobileWallet.productModel) &&
        Objects.equals(this.deviceId, scaWalletObjectScaWalletsInnerMobileWallet.deviceId) &&
        Objects.equals(this.deviceIdType, scaWalletObjectScaWalletsInnerMobileWallet.deviceIdType) &&
        Objects.equals(this.productFingerprint, scaWalletObjectScaWalletsInnerMobileWallet.productFingerprint) &&
        Objects.equals(this.secretFingerprint, scaWalletObjectScaWalletsInnerMobileWallet.secretFingerprint) &&
        Objects.equals(this.root, scaWalletObjectScaWalletsInnerMobileWallet.root) &&
        Objects.equals(this.pushMessagingId, scaWalletObjectScaWalletsInnerMobileWallet.pushMessagingId) &&
        Objects.equals(this.pushMessagingProvider, scaWalletObjectScaWalletsInnerMobileWallet.pushMessagingProvider) &&
        Objects.equals(this.mobileUpdateDate, scaWalletObjectScaWalletsInnerMobileWallet.mobileUpdateDate) &&
        Objects.equals(this.lastEligibilityCheck, scaWalletObjectScaWalletsInnerMobileWallet.lastEligibilityCheck) &&
        Objects.equals(this.nfc, scaWalletObjectScaWalletsInnerMobileWallet.nfc) &&
        Objects.equals(this.emulator, scaWalletObjectScaWalletsInnerMobileWallet.emulator) &&
        Objects.equals(this.appleTeamId, scaWalletObjectScaWalletsInnerMobileWallet.appleTeamId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appBuildNumber, sdkVersion, os, osVersion, brand, productModel, deviceId, deviceIdType, productFingerprint, secretFingerprint, root, pushMessagingId, pushMessagingProvider, mobileUpdateDate, lastEligibilityCheck, nfc, emulator, appleTeamId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScaWalletObjectScaWalletsInnerMobileWallet {\n");
    sb.append("    appBuildNumber: ").append(toIndentedString(appBuildNumber)).append("\n");
    sb.append("    sdkVersion: ").append(toIndentedString(sdkVersion)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    productModel: ").append(toIndentedString(productModel)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    deviceIdType: ").append(toIndentedString(deviceIdType)).append("\n");
    sb.append("    productFingerprint: ").append(toIndentedString(productFingerprint)).append("\n");
    sb.append("    secretFingerprint: ").append(toIndentedString(secretFingerprint)).append("\n");
    sb.append("    root: ").append(toIndentedString(root)).append("\n");
    sb.append("    pushMessagingId: ").append(toIndentedString(pushMessagingId)).append("\n");
    sb.append("    pushMessagingProvider: ").append(toIndentedString(pushMessagingProvider)).append("\n");
    sb.append("    mobileUpdateDate: ").append(toIndentedString(mobileUpdateDate)).append("\n");
    sb.append("    lastEligibilityCheck: ").append(toIndentedString(lastEligibilityCheck)).append("\n");
    sb.append("    nfc: ").append(toIndentedString(nfc)).append("\n");
    sb.append("    emulator: ").append(toIndentedString(emulator)).append("\n");
    sb.append("    appleTeamId: ").append(toIndentedString(appleTeamId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("appBuildNumber");
    openapiFields.add("sdkVersion");
    openapiFields.add("os");
    openapiFields.add("osVersion");
    openapiFields.add("brand");
    openapiFields.add("productModel");
    openapiFields.add("deviceId");
    openapiFields.add("deviceIdType");
    openapiFields.add("productFingerprint");
    openapiFields.add("secretFingerprint");
    openapiFields.add("root");
    openapiFields.add("pushMessagingId");
    openapiFields.add("pushMessagingProvider");
    openapiFields.add("mobileUpdateDate");
    openapiFields.add("lastEligibilityCheck");
    openapiFields.add("nfc");
    openapiFields.add("emulator");
    openapiFields.add("appleTeamId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScaWalletObjectScaWalletsInnerMobileWallet
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScaWalletObjectScaWalletsInnerMobileWallet.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ScaWalletObjectScaWalletsInnerMobileWallet is not found in the empty JSON string", ScaWalletObjectScaWalletsInnerMobileWallet.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ScaWalletObjectScaWalletsInnerMobileWallet.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ScaWalletObjectScaWalletsInnerMobileWallet` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("appBuildNumber") != null && !jsonObj.get("appBuildNumber").isJsonNull()) && !jsonObj.get("appBuildNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `appBuildNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appBuildNumber").toString()));
      }
      if ((jsonObj.get("sdkVersion") != null && !jsonObj.get("sdkVersion").isJsonNull()) && !jsonObj.get("sdkVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sdkVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sdkVersion").toString()));
      }
      if ((jsonObj.get("os") != null && !jsonObj.get("os").isJsonNull()) && !jsonObj.get("os").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `os` to be a primitive type in the JSON string but got `%s`", jsonObj.get("os").toString()));
      }
      if ((jsonObj.get("osVersion") != null && !jsonObj.get("osVersion").isJsonNull()) && !jsonObj.get("osVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `osVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("osVersion").toString()));
      }
      if ((jsonObj.get("brand") != null && !jsonObj.get("brand").isJsonNull()) && !jsonObj.get("brand").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brand` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brand").toString()));
      }
      if ((jsonObj.get("productModel") != null && !jsonObj.get("productModel").isJsonNull()) && !jsonObj.get("productModel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productModel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productModel").toString()));
      }
      if ((jsonObj.get("deviceId") != null && !jsonObj.get("deviceId").isJsonNull()) && !jsonObj.get("deviceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deviceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deviceId").toString()));
      }
      if ((jsonObj.get("deviceIdType") != null && !jsonObj.get("deviceIdType").isJsonNull()) && !jsonObj.get("deviceIdType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deviceIdType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deviceIdType").toString()));
      }
      if ((jsonObj.get("productFingerprint") != null && !jsonObj.get("productFingerprint").isJsonNull()) && !jsonObj.get("productFingerprint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productFingerprint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productFingerprint").toString()));
      }
      if ((jsonObj.get("secretFingerprint") != null && !jsonObj.get("secretFingerprint").isJsonNull()) && !jsonObj.get("secretFingerprint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secretFingerprint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secretFingerprint").toString()));
      }
      if ((jsonObj.get("root") != null && !jsonObj.get("root").isJsonNull()) && !jsonObj.get("root").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `root` to be a primitive type in the JSON string but got `%s`", jsonObj.get("root").toString()));
      }
      if ((jsonObj.get("pushMessagingId") != null && !jsonObj.get("pushMessagingId").isJsonNull()) && !jsonObj.get("pushMessagingId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pushMessagingId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pushMessagingId").toString()));
      }
      if ((jsonObj.get("pushMessagingProvider") != null && !jsonObj.get("pushMessagingProvider").isJsonNull()) && !jsonObj.get("pushMessagingProvider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pushMessagingProvider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pushMessagingProvider").toString()));
      }
      if ((jsonObj.get("mobileUpdateDate") != null && !jsonObj.get("mobileUpdateDate").isJsonNull()) && !jsonObj.get("mobileUpdateDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mobileUpdateDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mobileUpdateDate").toString()));
      }
      if ((jsonObj.get("appleTeamId") != null && !jsonObj.get("appleTeamId").isJsonNull()) && !jsonObj.get("appleTeamId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `appleTeamId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appleTeamId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScaWalletObjectScaWalletsInnerMobileWallet.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScaWalletObjectScaWalletsInnerMobileWallet' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScaWalletObjectScaWalletsInnerMobileWallet> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScaWalletObjectScaWalletsInnerMobileWallet.class));

       return (TypeAdapter<T>) new TypeAdapter<ScaWalletObjectScaWalletsInnerMobileWallet>() {
           @Override
           public void write(JsonWriter out, ScaWalletObjectScaWalletsInnerMobileWallet value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScaWalletObjectScaWalletsInnerMobileWallet read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScaWalletObjectScaWalletsInnerMobileWallet given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScaWalletObjectScaWalletsInnerMobileWallet
   * @throws IOException if the JSON string is invalid with respect to ScaWalletObjectScaWalletsInnerMobileWallet
   */
  public static ScaWalletObjectScaWalletsInnerMobileWallet fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScaWalletObjectScaWalletsInnerMobileWallet.class);
  }

  /**
   * Convert an instance of ScaWalletObjectScaWalletsInnerMobileWallet to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

